<a href="https://colab.research.google.com/github/Eafit-Ingenieria-Agronomica/Agricultura-Predictiva-2025_II/blob/main/Talleres/Taller_2/Imputación.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab"/></a>

## Agricultura Predictiva
### Taller _2: Exploración y limpieza de datos

<img src='https://upload.wikimedia.org/wikipedia/commons/a/ad/Plodozmian.jpg' width="1200" height="1000">

Fuente imagen: wikipedia


---

#**Análisis del Rendimiento de Cultivos**

La predicción del rendimiento de los cultivos es un problema agrícola importante. El rendimiento agrícola depende principalmente de las condiciones climáticas (lluvia, temperatura, etc.), de los pesticidas, y de contar con información precisa sobre el historial de rendimiento de los cultivos, lo cual es clave para tomar decisiones relacionadas con la gestión de riesgos agrícolas y las predicciones futuras. En este taller, se usarán datos de rendimiento de los diez cultivos más consumidos en el mundo según el sitio web de la FAO y modificados con fines didácticos. Los datos recopilados incluyen país, ítem (tipo de cultivo), año (desde 1961 hasta 2016) y el valor del rendimiento.

Estos cultivos incluyen:

* Yuca
* Maíz
* Plátanos y otros
* Papas
* Arroz (arroz con cáscara)
* Sorgo
* Soya
* Camote
* Trigo
* Ñame

cultivos (en ingles nombre original):

- Cassava                
- Maize                  
- Plantains and others   
- Potatoes                
- Rice, paddy             
- Sorghum                
- Soybeans               
- Sweet potatoes       
- Wheat                  
- Yams  
---

#1.Importar las librerias

In [1]:
# importar librerías
import numpy as np
import pandas as pd

In [2]:
#montar google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#**2.Datos de rendimiento de cultivos** 📈

##Leer datos de Rendimiento de Cultivos

In [3]:
df_yield=pd.read_csv('/content/drive/MyDrive/Predictiva /taller_predictiva/produccion.csv')
df_yield #Leer datos tabulares usando pandas

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Year Code,Year,Unit,Value
0,QC,Crops,2,Afghanistan,5419,Yield,56,1961,1961,hg/ha,14000hg/ha
1,QC,Crops,2,Afghanistan,5419,Yield,56,1962,1962,hg/ha,14000hg/ha
2,QC,Crops,2,Afghanistan,5419,Yield,56,1963,1963,hg/ha,14260hg/ha
3,QC,Crops,2,Afghanistan,5419,Yield,56,1964,1964,hg/ha,14257hg/ha
4,QC,Crops,2,Afghanistan,5419,Yield,56,1965,1965,hg/ha,14400hg/ha
...,...,...,...,...,...,...,...,...,...,...,...
56715,QC,Crops,181,Zimbabwe,5419,Yield,15,2015,2015,hg/ha,19826hg/ha
56716,QC,Crops,181,Zimbabwe,5419,Yield,15,2016,2016,hg/ha,18294hg/ha
56717,QC,Crops,2,Afghanistan,5419,Yield,56,1963,1963,hg/ha,14260hg/ha
56718,QC,Crops,2,Afghanistan,5419,Yield,56,1961,1961,hg/ha,14000hg/ha
56719,QC,Crops,2,Afghanistan,5419,Yield,56,1965,1965,hg/ha,14400hg/ha

##Explorar datos

In [4]:
#Obtener shape de los datos (filas,columnas)
display(df_yield.shape)

(56720, 11)

In [ ]:
#Lista de los nombres de los campos de una tabla

In [ ]:
#Mostrar los primeras n filas(registros) del dataframe(tabla)

In [ ]:
#Mostrar las ultimas n filas(registros) del dataframe(tabla)

In [ ]:
#Descripción de la Información de la tabla y tipo de datos

##Selección preliminar de características

###Identificar campos con valores constantes, campos repetidos o redundantes

Los campos constantes son aquellos que tienen un mismo valor en todas sus celdas, por lo tanto el campo posee un solo valor único, una revisión visual de los primeros y últimos registros de la tabla puede sugerir posibles candidatos, pero no es confiable cuando el número de filas es grande, así que confirmamos los posibles campos constantes usando el método [.nunique()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html) de pandas.

In [ ]:
#Conteo de valores únicos por columna usando pandas

In [ ]:
#Revisar si un campo tiene todos sus valores igual a otro campo por ejemplo "Year" y "Year Code"
campo1="Year"
campo2="Year Code"

if np.array_equal(df_yield[campo1],df_yield[campo2]) == True:
    print("campo1 y campo2 son iguales") #imprime si ambos campos son iguales

In [ ]:
# Descartar columnas no deseadas (conservando el orden de las columnas restantes).

##Relacionar tablas por un campo en común

El campo “Item Code” guarda el código de cultivo para cada registro, así que éste puede ser usado como campo clave para relacionar las tablas de producción y de códigos de cultivos. De esta manera se logra tener en una sola tabla la información de producción y los nombres de los cultivos

In [ ]:
codigo_cultivos_df= #Leer tabla con los códigos de cultivos

In [ ]:
#relacionar las tablas de producción y de códigos de cultivos por el campo "Item_Code". Use el método merge de pandas.

In [ ]:
# Descripción de la información de la tabla anterior y tipo de datos

In [ ]:
#Con base en la tabla anterior seleccionar los campos deseados y con un orden específico 'Area','Item','Year','Value'

##Limpieza de datos

#### Cambiar nombres de campos (Renombrar columnas): Al observar los nombres de las columnas, podemos renombrar 'Value' a 'hg/ha_yield' para que sea más fácil reconocer que éste es el valor de producción/rendimiento de los cultivos.

In [ ]:
# Renombrar columnas. Use el metodo rename de pandas

###Identificar nulos (NaN)

In [ ]:
#Contar cantidad de valores nulos por campo(columna)

In [ ]:
# porcentaje de nulos por columna

**Muchos algoritmos no admiten valores nulos** o generan resultados erróneos o sin sentido al operar sobre este tipo de datos, por lo tanto antes de efectuar operaciones con los valores de la tabla **las filas que poseen estos valores nulos deben ser identificadas**

In [ ]:
# Calcular porcentaje de filas con al menos un NaN

In [ ]:
#Mostrar las filas con valores nulos

###Eliminar filas con valores nulos

Antes de eliminar filas con valores nulos, evalúa:

¿Qué columnas están afectadas?: si las columnas afectadas no son importantes, elimina las columnas.

¿Qué porcentaje del total de las filas representan?: Para este ejercicio si el porcentaje es bajo, menor de un 20%, asumimos que eliminar los registros no causará problemas para aplicar métodos de regresión.

¿Puedes o debes imputar en lugar de eliminarlos?: El valor faltante se puede estimar o imputar, por ejemplo puedes imputar con la media, mediana o usar técnicas de imputación más avanzadas. Pero es importante tener en cuenta que entre más complejos los datos, más difícil es encontrar un valor que se ajuste correctamente a las dinámicas presentes en los datos.

**Para estos datos en particular, dada la baja cantidad de filas con valores nulos se decide eliminarlas**

In [ ]:
#imprimir shape de la tabla (filas, columnas) antes de eliminar registros con valores nulos para comparar.

In [ ]:
#Eliminar filas con valores nulos (usar cuando la cantidad relativa de filas con nulos es baja, menor del 20% )
#imprimir shape

In [ ]:
#Descripción de la Información de la tabla y tipo de datos

### Convertir un campo tipo object a float

In [ ]:
#Eliminar los caracteres'hg/ha'de todas las celdas del campo rendimiento para poder transformar el campo a numérico

In [ ]:
# convertir el campo 'hg/ha_yield' de tipo object a float.
#puede usar este codigo como ejemplo df_yield['hg/ha_yield'] = pd.to_numeric(df_yield['hg/ha_yield'], errors='coerce')

In [ ]:
#Descripción de la Información de la tabla y tipo de datos

In [ ]:
# Resumen de estadísticas

#**3.Datos Climáticos: Precipitación** 💧
Los factores climáticos como la precipitación, forma parte de los multiples factores ambientales que influyen en el crecimiento y desarrollo de un cultivo. Para este ejercicio, se recopiló información sobre la precipitación anual del [Banco Mundial](https://datos.bancomundial.org/).

##Leer datos

In [ ]:
df_rain = #Leer datos tabulares usando pandas

##Explorar datos

In [ ]:
#Obtener shape de los datos (filas,columnas)

In [ ]:
#Lista de los nombres de los campos de una tabla

In [ ]:
#Mostrar las primeras n filas

In [ ]:
#Mostrar las ultimas n filas

In [ ]:
#Descripción de la Información de la tabla y tipo de datos

In [ ]:
# Resumen de estadísticas

##Selección preliminar de características

###Identificar campos con valores constantes, campos repetidos o redundantes

In [ ]:
#Conteo de valores únicos por columna usando pandas

##Limpieza de datos

###Cambiar nombres de campos (Renombrar columnas)
Al observar los nombres de los campos, podemos cambiar ' Area' por 'Area' para mantener la consistencia con la tabla base de redimiento y evitar problemas a la hora de trabajar o buscar el nombre de este campo.

In [ ]:
# Renombrar campo

### Convertir un campo de tipo object a float

In [ ]:
# convertir el campo average_rain_fall_mm_per_year de tipo object a float

###Identificar nulos (NaN)

In [ ]:
# Calcular porcentaje de nulos por columna

In [ ]:
# Calcular porcentaje de filas con al menos un NaN

In [ ]:
#Mostrar las filas con valores nulos

###Eliminar filas con valores nulos

In [ ]:
#imprimir shape (filas, columnas) de la tabla antes de la eliminación para comparar

In [ ]:
#Eliminar filas con valores nulos (usar cuando la cantidad relativa de filas con nulos es baja, menor del 20% )
#imprimir shape

In [ ]:
#Descripción de la Información de la tabla y tipo de datos

El dataframe de precipitaciones comienza en 1985 y finaliza en 2017. Revisa el dataframe de producción , en qué año comienza y termina?

A continuación combine la tabla de producción con la tabla de precipitación usando el método merge de pandas y las columnas de year y area como campos clave.

##Relacionar tablas por 2 campos clave

In [ ]:
# relacionar el dataframe de rendimiento con el dataframe de precipitación por las columnas 'Year'y 'Area'
# con el objetivo de obtener los registros con informacion de la precipitación por año

Ahora, observamos la forma final del *dataframe* y la información de los valores:

In [ ]:
# imprimir shape (filas, columnas) de la tabla

In [ ]:
# mostrar los primeros n registros

In [ ]:
# Revisar si hay nulos

In [ ]:
#Eliminar nulos

In [ ]:
# Resumen de estadísticas

Podemos ver que ahora los años comienzan desde 1985, mientras que en el primer *dataframe* de rendimiento el año inicial era 1961; esto se debe a que los datos de precipitación comienzan en 1985.

# **4.Datos de Pesticidas:** ☠

Los pesticidas utilizados para cada producto y país también fueron recopilados de la base de datos de la FAO.

##Leer datos

In [ ]:
df_pes = #Leer datos tabulares usando pandas

##Explorar datos

In [ ]:
#Obtener shape de los datos (filas,columnas)

In [ ]:
#Lista de los nombres de los campos de una tabla

In [ ]:
# mostrar los primeros n registros

In [ ]:
#mostrar los ultimos n resgistros

In [ ]:
#Descripción de la Información de la tabla y tipo de datos

In [ ]:
# Resumen de estadísticas

##Selección preliminar de características

###Identificar campos constantes, repetidos o redundantes

In [ ]:
#Conteo de valores únicos por columna usando pandas

In [ ]:
# Eliminar columnas no deseadas (conservando el orden de las columnas restantes).

##Limpieza de datos

###Cambiar nombres de campos (Renombrar columnas)

In [ ]:
#cambiar el nombre del campo "Value" por "pesticides_tonnes"

In [ ]:
#Descripción de la Información de la tabla y tipo de datos

### Convertir un campo de tipo object a float

In [ ]:
#Eliminar los caracteres "tonnes" de cada celda del campo 'pesticides_tonnes' para poder transformar el campo a un campo numérico

In [ ]:
# convertir el campo 'pesticides_tonnes' de tipo object a float.

###Identificar nulos (NaN)

In [ ]:
# contar valores nulos (no hay valores nulos en este dataframe)

###Eliminar filas con valores nulos

In [ ]:
#Eliminar filas con valores nulos (usar cuando la cantidad relativa de filas con nulos es baja, menor del 20% )#

###Relacionar tablas por 2 campos clave

In [ ]:
# relacionar el *dataframe* de rendimiento con el *dataframe* de pesticidas usando los campos de 'Year','Area'

In [ ]:
# mostrar los primeros n registros

In [ ]:
#Descripción de la Información de la tabla y tipo de datos

In [ ]:
# Resumen de estadísticas

# **5.Datos Temperatura Promedio:** 🔥

La temperatura promedio de cada país fue recopilada de los datos del Banco Mundial.

## Leer datos

In [ ]:
avg_temp= # Leer archivo JSON directamente con pandas

##Explorar datos

In [ ]:
#imprimir shape

In [ ]:
# mostar los primeros n registros

In [ ]:
# mostrar los ultimos n registros

In [ ]:
#Descripción de la Información de la tabla y tipo de datos

In [ ]:
#Resumen de stadísticas

Entonces, la temperatura promedio comienza en 1743 y termina en 2013, con algunas filas vacías que debemos eliminar.

## Selección prelimnar de características

###Identificar campos con valores constantes, campos repetidos o redundantes

In [ ]:
#Conteo de valores únicos por columna usando pandas

##Limpieza de datos

###Cambiar nombres de campos (Renombrar columnas)

In [ ]:
# Cambair el nombre del campo "year"por "Year" y "country" por 'Area' para que sean consistentes con las demas tablas

###Identificar nulos

In [ ]:
# porcentaje de nulos por columna

In [ ]:
# Calcular porcentaje de filas con al menos un NaN

In [ ]:
#Mostrar las filas con valores nulos

###Eliminar filas con valores nulos

In [ ]:
#Por defecto elimina las filas que poseen algún valor nulo

##Relacionar tablas por 2 campos clave

In [ ]:
# relacionar el *dataframe* de rendimiento con el *dataframe* de temperatura  por los campos 'Area','Year'

In [ ]:
#Obtener shape de los datos (filas,columnas)

In [ ]:
# Resumen de estadísticas de la tabla final

In [ ]:
# Revisar si hay nulos

¡Genial, no hay valores vacíos!

In [ ]:
#Descripción de la Información de la tabla final y tipo de datos

##Registros duplicados

In [ ]:
# explorar registros duplicados

In [ ]:
#Eliminar registros duplicados

In [ ]:
##Ejemplo de tabla resultado, no debe contener nulos ni duplicados y los últimos 4 campos deben ser numéricos

,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,Albania,Maize,1990,36613,1485.0,121.00,16.37
1,Albania,Maize,1991,29068,1485.0,121.00,15.36
2,Albania,Maize,1992,24876,1485.0,121.00,16.06
3,Albania,Maize,1993,24185,1485.0,121.00,16.05
4,Albania,Maize,1994,25848,1485.0,201.00,16.96
...,...,...,...,...,...,...,...
28242,Zimbabwe,Wheat,2009,30000,657.0,3269.99,20.52
28243,Zimbabwe,Wheat,2010,27681,657.0,3305.17,21.17
28244,Zimbabwe,Wheat,2011,26274,657.0,3340.35,20.78
28245,Zimbabwe,Wheat,2012,24420,657.0,3375.53,20.52
28246,Zimbabwe,Wheat,2013,22888,657.0,2550.07,19.76

# **6.Datos consolidados** 📊

**yield_df** es el *dataframe* final obtenido.

In [ ]:
#Agrupar los datos por tipo de cultivo y contar la cantidad de registros asociados a cada grupo (cultivo)
yield_df.groupby('Item').count()

In [ ]:
# cuántos valores únicos(areas,zonas o paises) hay?

In [ ]:
#Mostrar nombre de todos los paises
#¿Está Colombia…?

In [ ]:
# Pasar el campo Area a minuscula

In [ ]:
# Teniendo en cuenta los anterior¿cuántos resgistros corresponden a Colombia?

In [ ]:
# ordenar los paises de mayor a menor rendiemiento y mostrar los 10 primeros
#yield_df.groupby(['Area'],sort=True)['hg/ha_yield'].sum().nlargest(10)

In [ ]:
#Cuál pais tiene mayor producción por tipo de cultivo? mostrar los 10 primeros